on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: |
          sudo apt update
          sudo apt install build-essential libgtk-4-dev libadwaita-1-dev
      - run: cargo build --release
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-type: rust
      - run: cargo publish --token ${CRATES_TOKEN}
        if: ${{ steps.release.outputs.release_created }}
        env:
          CRATES_TOKEN: ${{secrets.CRATES_TOKEN}}
      - name: Upload binaries to release
        if: ${{ steps.release.outputs.release_created }}
        run: |
          mv ./target/release/pipemenu pipemenu_${{ steps.release.outputs.tag_name }}_linux-64bit
          gh release upload ${{ steps.release.outputs.tag_name }} pipemenu_${{ steps.release.outputs.tag_name }}_linux-64bit
        env:
          GH_TOKEN: ${{ github.token }}
